#!/bin/bash

#This file was created by Ricardo Mello -> github/ricardohsmello

<<COMMENT1
This file will be executed in git's pre-push. 
If the repository is the 'master', 
the script will ask if you want to generate a tag from the master.
If so, it will generate and submit the tag.
COMMENT1

#This commands makes terminal promp accessible
exec < /dev/tty

#This command gets the name of the current branch
current_branch=$(git branch | grep "*" | sed "s/\* //")

#This command gets the name of the merge branch
reflog_message=$(git reflog -1)
merged_branch_name=$(echo $reflog_message | cut -d" " -f 4 | sed "s/://")

# if the merged branch is master, exit
if [[ $merged_branch_name = "master" ]]; then
    exit 0
fi

echo "Você acabou de realizar um merge do branch \"$merged_branch_name\" para o \"$current_branch\". "

read -p "Deseja excluir o branch \"$merged_branch_name\" ? (y/N) " answer

if [[ "$answer" == "y" ]]; then
    # Deleting the local branch
    echo "Excluindo o branch localmente \"$merged_branch_name\""
    git branch -d $merged_branch_name

    # Deleting the remote branch
    echo "Excluindo o branch remotamente"
    git push origin --delete $merged_branch_name    
    exit 1
else
    echo "Branch -> \"$merged_branch_name\" mantido."
fi
