#!/bin/bash

#This file was created by Ricardo Mello -> github/ricardohsmello

<<COMMENT1
This file will be executed in git's pre-push. 
If the repository is the 'master', 
the script will ask if you want to generate a tag from the master.
If so, it will generate and submit the tag.
COMMENT1

#This commands makes terminal promp accessible
exec < /dev/tty
 
#This command gets the name of the current branch
current_branch=$(git branch | grep "*" | sed "s/\* //")

#Deleting the temporary branch of this logic
if [[ $current_branch = "tmpBranch" ]]; then
	git checkout master
	git branch -D tmpBranch
fi 

#Verifying if the current branch is Master
if [[ $current_branch = "master" ]]; then

	echo " "
	echo "Você acabou de submeter seu repositório Master."

	read -p "Deseja gerar uma tag a partir dele? (y/N)" answer

	if [[ "$answer" == "y" ]]; then
		read -p "Informe o nome da tag. Ex: v.0.1: " tagname
		git tag "$tagname"
		echo "Tag \"$tagname\" gerada com sucesso"
		git checkout -b tmpBranch
		echo "Submetendo tag no servidor remoto.."
		git push $(git remote) "$tagname"		
	fi

fi
